socket_address:
  ip_address: "0.0.0.0"
  port: "8080"
service_type: "ggml/llama2"
services:
  - path: "/v1/chat/completions"
    target_service: "https://api.openai.com/v1/chat/completions"
    ty: "openai"
  - path: "/v1/completions"
    target_service: "https://api.openai.com/v1/completions"
    ty: "openai"
  - path: "/v1/embeddings"
    target_service: "https://api.openai.com/v1/embeddings"
    ty: "openai"
  - path: "/v1/models"
    target_service: "https://api.openai.com/v1/models"
    ty: "openai"
  - path: "/v1/chat/completions"
    target_service: ""
    ty: "ggml/llama2"
  - path: "/v1/completions"
    target_service: ""
    ty: "ggml/llama2"
  - path: "/v1/embeddings"
    target_service: ""
    ty: "ggml/llama2"
  - path: "/v1/models"
    target_service: ""
    ty: "ggml/llama2"
  - path: "/echo"
    target_service: ""
    ty: "test"